In [5]:
import numpy as np

#1. Create a 1D array of numbers from 0 to 9

array = np.arange(0,10) #Print 1-D array
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
#2. Convert 1D array into 2D array with 2 rows

array = np.array([0,1,2,3,4,5,6,7,8,9]) #CREATES 2-D ARRAY FROM 1-D ARRAY
print(array)
print("")
newarray = array.reshape(2,5) # Creates 2 array with 5 elements each.
print(newarray)


[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
#3. Write a NumPy program to create an array of the integers from 30 to 70.

array = np.arange(30,71) #Function arange prints numbers from specified ranges
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [57]:
#4. Write a NumPy program to append values to the end of an array.

arr = [1,2,3,4,5] #Appends arr2 onto arr
arr = np.append(arr, [[6, 7, 8]])
print(arr)



[1 2 3 4 5 6 7 8]


In [29]:
#Ext 1: Write a NumPy program to find the number of rows and columns of a given matrix.

import numpy as np

matrix= np.arange(12,24).reshape((3, 4)) #3 rows and 4 columns
print(matrix)
print("Rows and columns of matrix:")
print(matrix.shape)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rows and columns of matrix:
(3, 4)


In [7]:
#2. Write a NumPy program to create an array of all the even integers from 30 to 70

array=np.arange(30,71,2) # 30 to 70 in 2 increments

print("Even Integers from 30 to 70")
print(array) 

Even Integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [46]:
#3. Write a NumPy program to convert a list and tuple into arrays.
list = [1, 2, 3, 4, 5, 6, 7, 8]
print(np.asarray(list))

tuple = ([8, 7, 6], [5, 4, 3]) #Convert tubple to array
print("Tuple to array: ")
print(np.asarray(tuple))

[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 7 6]
 [5 4 3]]


In [66]:
#1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise
print("Subtract:")
print(np.subtract(12,5))

print("Addition:")
print(np.add(12,5))

print("Multiplication:")
print(np.multiply(12,5))

print("Division:") 
print(np.divide(12,5))

Subtract:
7
Addition:
17
Multiplication:
60
Division:
2.4


In [83]:
#2. Write a NumPy program to round elements of the array to the nearest integer.

array = [1.1,2.2,4.6,4.7]
array = np.around(array,0) 
print(array)

[1. 2. 5. 5.]


In [90]:
#3. Write a NumPy program to get true division of the element-wise array inputs.

array = [10,20,30,40]
print(np.true_divide(array,4))

[ 2.5  5.   7.5 10. ]


In [52]:
#1. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.
import numpy as np
x = np.random.random((5,3)) # creates 5x3 matrix filled with random floats
print("First array:")
print(x)
y = np.random.random((3,2)) # creates 3x2 matrix filled with random floats
print("Second array:")
print(y)
z = np.dot(x, y) # The "Dot Product" is where we multiply matching members, then sum up
print("Dot product of two arrays:")
print(z)

First array:
[[0.13702467 0.72270273 0.95431046]
 [0.43172761 0.04044322 0.49230668]
 [0.5878322  0.59572888 0.87013487]
 [0.61951756 0.12492983 0.92197838]
 [0.18799529 0.56604049 0.60190526]]
Second array:
[[0.14053515 0.85485871]
 [0.19872273 0.48865396]
 [0.89245224 0.53361804]]
Dot product of two arrays:
[[1.01455074 0.97952555]
 [0.50807008 0.65153257]
 [0.97754977 1.25793842]
 [0.93471205 1.08263173]
 [0.67607675 0.75849484]]


In [56]:
#2. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.
import numpy as np

x = np.random.randn(100)
print("Average of the array elements:")

mean = x.mean()
print(mean)

print("Standard deviation of the array elements:")
std = x.std()
print(std)

print("Variance of the array elements:")
var = x.var()
print(var)

Average of the array elements:
-0.019495678424513586
Standard deviation of the array elements:
1.0032765370040198
Variance of the array elements:
1.006563809702778


In [45]:
#4. Write a Python program to find the maximum and minimum value of 1D array.

array = np.arange(12).reshape((4,3))
print("Array:")
print(array)

print("Max Value of array:")
print(np.amax(array))
print("Min Value of array:")
print(np.amin(array))

Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Max Value of array:
11
Min Value of array:
0
